version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: desafio_tecnico
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - desafio_pg_data:/var/lib/postgresql/data

volumes:
  desafio_pg_data: